create table
  public.folders (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    color text null,
    size smallint null,
    user_id uuid null,
    folder_id bigint null,
    fixed boolean null,
    type text null,
    constraint folders_pkey primary key (id),
    constraint folders_name_key unique (name)
  ) tablespace pg_default;

create table
  public.files (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    url text null,
    size text null,
    fixed boolean null,
    user_id uuid null,
    folder_id bigint null,
    constraint files_pkey primary key (id),
    constraint files_folder_id_fkey foreign key (folder_id) references folders (id)
  ) tablespace pg_default;